services:
  backend_api:
    build: ./ToDoListBackend
    container_name: to_do_list_api
    ports:
      - "8080:8080"
    environment:
      - DB_SERVER=database_sql
      - DB_PORT=1433
      - DB_DATABASE=todolistDB
      - DB_PASSWORD=mi_password_secreta123
    depends_on:
      - database_sql
    networks:
      - todo_network

  database_sql:
    #custom image running sql scripts
    #build: ./DatabaseSql
    #original image from ms
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sql_db_dev
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: mi_password_secreta123
    ports:
      - "1433:1433"
    volumes:
      # 1. Persistencia de datos:
      - db_data_dev:/var/opt/mssql
    networks:
      - todo_network

volumes:
  db_data_dev:
networks:
  todo_network:

